# Generated by Django 4.2.5 on 2023-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_wallpaper_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image_url',
            field=models.ImageField(upload_to='static/wallpapers'),
        ),
    ]
