# Generated by Django 4.2.5 on 2023-09-19 06:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wallpaper_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_pack', models.FileField(upload_to=api.models.generate_iconpackname)),
                ('tags', models.ManyToManyField(related_name='icon_packs', to='api.tag')),
            ],
        ),
    ]
